In [1]:
import numpy as np

In [65]:
class BAM:
    def __init__(self, input_shape, output_shape):
        self.weights = np.zeros((input_shape, output_shape))

    def train(self, input_pattern, output_pattern):
        for i in range(input_pattern.shape[0]):
            x = input_pattern[i]
            y = output_pattern[i]

            self.weights += np.outer(x, y)

    # Recall output patterns
    def recall_X_Y(self, input_pattern):
        return np.dot(self.weights, input_pattern)

    # Recall input patterns
    def recall_Y_X(self, output_pattern):
        return np.dot(self.weights, output_pattern)


In [66]:
input_size = 2
output_size = 2
bam = BAM(input_size, output_size)

In [67]:
input_pattern = np.array([[1,-1], [-1,1]])
output_pattern = np.array([[-1,1], [1,-1]])

bam.train(input_pattern, output_pattern)

In [68]:
bam.weights

array([[-2.,  2.],
       [ 2., -2.]])

In [69]:
#Testing input to output
input_pattern = np.array([1,-1])
bam.recall_X_Y(input_pattern)

array([-4.,  4.])

In [72]:
output_pattern = np.array([1,-1])
bam.recall_Y_X(output_pattern)

array([-4.,  4.])